name: eslint
on: [pull_request]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'testdata/javascript/'
